# Generated by Django 3.1.6 on 2021-03-09 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210226_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='api.map'),
        ),
        migrations.AlterField(
            model_name='route',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='api.map'),
        ),
    ]
